### ISSUE TITLE
Corner points are not removed

### ISSUE THREAD

**Issue by frankrolf** [roboDocs/CornerTools#3]
Sorry for the noise, I am not sure my comment to a closed issue will stay on the radar – for awareness’ sake, here it is again:

The fix to #2 breaks the non-interactive corner rounding in the following way:
https://www.dropbox.com/s/7p2g739i9vt5i1f/corner.mov?dl=0

**Comment by typoman** [comment]
I have the exact same issue. Strange in RF1 it didn't happen.

**Comment by frankrolf** [comment]
@typoman If you undo #2 it’ll work

**Comment by typoman** [comment]
Thanks Frank! I realized that also after I went to commit you mentioned!
