### ISSUE TITLE
Mechanic failure

### ISSUE THREAD

**Issue by typoman** [roboDocs/CornerTools#4]
I get this in RF3:
```Could not download the extension zip file for: 'CornerTools'```

**Comment by gferreira** [comment]
hello @typoman,

I’ve just tried it out, it worked fine… I can install and use the tool without any problem.

maybe it was just a temporary connection glitch? can you please try again? thanks

**Comment by typoman** [comment]
That's right I can't download other extensions either. Will investigate! Thanks and sorry!

**Comment by typoman** [comment]
Reinstalling mechanic from its website fixed the issue.
